DateLab_lin.exe : priorityqueue.o
	gcc -Wall -std=c99 -finput-charset=GBK -fexec-charset=GBK -static -g -o DateLab_lin.exe priorityqueue.o
priorityqueue.o : priorityqueue.c Priority_Queue.h
	gcc -Wall -std=c99 -finput-charset=GBK -fexec-charset=GBK -static -g -c priorityqueue.c