# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/WE.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/seven_segment.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/REGISTER.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/CONTROL.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/dclok.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/MEMWB.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/choose_seg.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/HAZARD.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/BY_PATH.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/RAM_DATA.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/EXMEM.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/ROM_INSTRUCTION.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/REGFILE.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/IFID.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/IDEX.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/ALU_MIPS.v
  /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/sources_1/new/MIPS_CPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/constrs_1/new/MIPS_CPU_T.xdc
set_property used_in_implementation false [get_files /home/strawberrylin/Xilinx/VerilogProject/project_1/project_1.srcs/constrs_1/new/MIPS_CPU_T.xdc]


synth_design -top MIPS_CPU -part xc7a100tcsg324-1


write_checkpoint -force -noxdef MIPS_CPU.dcp

catch { report_utilization -file MIPS_CPU_utilization_synth.rpt -pb MIPS_CPU_utilization_synth.pb }
