# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.cache/wt [current_project]
set_property parent.project_path /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/sources_1/new/dclock_1000Hz.v
  /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/sources_1/new/seven_segment.v
  /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/sources_1/new/display_module.v
  /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/sources_1/new/main_module.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/constrs_1/new/liftdesign_t.xdc
set_property used_in_implementation false [get_files /home/strawberrylin/gitrepository/VerilogCourseDesign/flatdesign/flatdesign.srcs/constrs_1/new/liftdesign_t.xdc]


synth_design -top main_module -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main_module.dcp

catch { report_utilization -file main_module_utilization_synth.rpt -pb main_module_utilization_synth.pb }
