# Nexys4 Pin Assignments
############################
# On-board Slide Switches  #
############################
# Clk Sclk Reset K0 K1 K2 K3
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E16 [get_ports in_require[0]]
set_property IOSTANDARD LVCMOS33 [get_ports in_require[0]]
set_property PACKAGE_PIN R10 [get_ports in_require[1]]
set_property IOSTANDARD LVCMOS33 [get_ports in_require[1]]
set_property PACKAGE_PIN V10 [get_ports in_require[2]]
set_property IOSTANDARD LVCMOS33 [get_ports in_require[2]]
set_property PACKAGE_PIN T16 [get_ports in_require[3]]
set_property IOSTANDARD LVCMOS33 [get_ports in_require[3]]
set_property PACKAGE_PIN U9 [get_ports out_uprequire[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out_uprequire[0]]
set_property PACKAGE_PIN U8 [get_ports out_uprequire[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out_uprequire[1]]
set_property PACKAGE_PIN R7 [get_ports out_downrequire[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out_downrequire[0]]
set_property PACKAGE_PIN R6 [get_ports out_uprequire[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out_uprequire[2]]
set_property PACKAGE_PIN R5 [get_ports out_downrequire[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out_downrequire[1]]
set_property PACKAGE_PIN V7 [get_ports out_downrequire[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out_downrequire[2]]
set_property PACKAGE_PIN P4 [get_ports power]
set_property IOSTANDARD LVCMOS33 [get_ports power]
set_property PACKAGE_PIN P3 [get_ports open]
set_property IOSTANDARD LVCMOS33 [get_ports open]
set_property PACKAGE_PIN R3 [get_ports close]
set_property IOSTANDARD LVCMOS33 [get_ports close]





############################
# On-board led             #
############################
# Dout Sout  8bits
set_property PACKAGE_PIN M4 [get_ports Dataout[7]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[7]]
set_property PACKAGE_PIN L3 [get_ports Dataout[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[6]]
set_property PACKAGE_PIN N1 [get_ports Dataout[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[5]]
set_property PACKAGE_PIN L5 [get_ports Dataout[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[4]]
set_property PACKAGE_PIN L4 [get_ports Dataout[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[3]]
set_property PACKAGE_PIN K3 [get_ports Dataout[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[2]]
set_property PACKAGE_PIN M2 [get_ports Dataout[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[1]]
set_property PACKAGE_PIN L6 [get_ports Dataout[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Dataout[0]]
# Segout 8bits
set_property PACKAGE_PIN N6 [get_ports Segout[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[0]]
set_property PACKAGE_PIN M6 [get_ports Segout[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[1]]
set_property PACKAGE_PIN M3 [get_ports Segout[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[2]]
set_property PACKAGE_PIN N5 [get_ports Segout[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[3]]
set_property PACKAGE_PIN N2 [get_ports Segout[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[4]]
set_property PACKAGE_PIN N4 [get_ports Segout[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[5]]
set_property PACKAGE_PIN L1 [get_ports Segout[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[6]]
set_property PACKAGE_PIN M1 [get_ports Segout[7]]
set_property IOSTANDARD LVCMOS33 [get_ports Segout[7]]
# Ring Light

set_property PACKAGE_PIN P2 [get_ports powerled]
set_property IOSTANDARD LVCMOS33 [get_ports powerled]
set_property PACKAGE_PIN R2 [get_ports openled]
set_property IOSTANDARD LVCMOS33 [get_ports openled]
set_property PACKAGE_PIN U1 [get_ports closeled]
set_property IOSTANDARD LVCMOS33 [get_ports closeled]
set_property PACKAGE_PIN P5 [get_ports upled]
set_property IOSTANDARD LVCMOS33 [get_ports upled]
set_property PACKAGE_PIN R1 [get_ports downled]
set_property IOSTANDARD LVCMOS33 [get_ports downled]

set_property PACKAGE_PIN T8 [get_ports up_requireled[0]]
set_property IOSTANDARD LVCMOS33 [get_ports up_requireled[0]]
set_property PACKAGE_PIN V9 [get_ports up_requireled[1]]
set_property IOSTANDARD LVCMOS33 [get_ports up_requireled[1]]
set_property PACKAGE_PIN R8 [get_ports down_requireled[0]]
set_property IOSTANDARD LVCMOS33 [get_ports down_requireled[0]]
set_property PACKAGE_PIN T6 [get_ports up_requireled[2]]
set_property IOSTANDARD LVCMOS33 [get_ports up_requireled[2]]
set_property PACKAGE_PIN T5 [get_ports down_requireled[1]]
set_property IOSTANDARD LVCMOS33 [get_ports down_requireled[1]]
set_property PACKAGE_PIN T4 [get_ports down_requireled[2]]
set_property IOSTANDARD LVCMOS33 [get_ports down_requireled[2]]

set_property PACKAGE_PIN U7 [get_ports in_requireled[0]]
set_property IOSTANDARD LVCMOS33 [get_ports in_requireled[0]]
set_property PACKAGE_PIN U6 [get_ports in_requireled[1]]
set_property IOSTANDARD LVCMOS33 [get_ports in_requireled[1]]
set_property PACKAGE_PIN V4 [get_ports in_requireled[2]]
set_property IOSTANDARD LVCMOS33 [get_ports in_requireled[2]]
set_property PACKAGE_PIN U3 [get_ports in_requireled[3]]
set_property IOSTANDARD LVCMOS33 [get_ports in_requireled[3]]